### ISSUE TITLE
Add `GC.monitor` functionality

### ISSUE THREAD

**Issue by mihails-strasuns-sociomantic** [sociomantic-tsunami/dmd-transitional#14]
D1 runtime provides GC monitor callbacks (https://github.com/sociomantic-tsunami/tangort/blob/32ad03f41da038b6e315931c551ddfe4cd0d26eb/src/core/memory.d#L478-L479) to run custom hooks on collection begin/end. Some of our apps use it for tracing/stats.

We need to propose similar functionality to upstream druntime and also add support to dmd-transitional. Foruntately it is not a language change as should work as a plain PR with no DIP.

**Comment by mihails-strasuns-sociomantic** [comment]
@mathias-lang-sociomantic has submitted WIP PR here https://github.com/dlang/druntime/pull/2052

**Comment by leandro-lucarella-sociomantic** [comment]
Can I convert this issue to "Add GC.monitor"? As we already have an issue upstream.

**Comment by mihails-strasuns-sociomantic** [comment]
Yes, sure.

**Comment by leandro-lucarella-sociomantic** [comment]
Closing as `wontfix` now that we are not going to pursue the issue upstream.
