### ISSUE TITLE
Drop 2.070 support

### ISSUE THREAD

**Issue by mihails-strasuns-sociomantic** [sociomantic-tsunami/dmd-transitional#17]
As soon as no tested library branch requires 2.070, we can delete the branch here.

FYI @leandro-lucarella-sociomantic

**Comment by mathias-lang-sociomantic** [comment]
That means dropping v6.x.x support in _the library_.
CC @andrej-mitrovic-sociomantic

**Comment by mihails-strasuns-sociomantic** [comment]
Sorry, `v6.x.x` of what?

**Comment by mihails-strasuns-sociomantic** [comment]
Just in case - there is nothing to worry about, I imply dropping support due to natural SemVer branch maintenance terms, no artificial speedup.

**Comment by andrej-mitrovic-sociomantic** [comment]
> of what

Of crocodile.

**Comment by mihails-strasuns-sociomantic** [comment]
Crocodiles. Why it has always to be crocodiles?

**Comment by mihails-strasuns** [comment]
Branch deleted. There are still some old library versions using it, but they will be fine with remaining tags.
