### ISSUE TITLE
Implement temporary solution for GC.monitor that matches D1 runtime

### ISSUE THREAD

**Issue by mihails-strasuns** [sociomantic-tsunami/dmd-transitional#31]
Until proper upstream version is implemented, temporary dmd-transitional solution should be provided to unblock progress in internal D2 migration in the meanwhile.

**Comment by mihails-strasuns** [comment]
(Previous issue which intended to match upstream impl https://github.com/sociomantic-tsunami/dmd-transitional/issues/14)

**Comment by leandro-lucarella-sociomantic** [comment]
Whatever is simpler, `GC.monitor` or adding the stats calculation to the GC. Anything that get users the time spent on the GC (and in particular in the collection).

**Comment by mihails-strasuns** [comment]
https://github.com/sociomantic-tsunami/dmd-transitional/pull/33
