### ISSUE TITLE
Error building dmd-transitional

### ISSUE THREAD

**Issue by gkotian** [sociomantic-tsunami/dmd-transitional#6]
I cloned this repository and tried to build it. But I ran into a lot of linking errors of the form:
```
/usr/bin/ld: /tmp/.host_dmd-2.068.2/dmd2/linux/bin64/../lib64/libphobos2.a(thread_215_713.o): relocation R_X86_64_32 against symbol `_D4core6thread17thread_entryPointUPvZ21thread_cleanupHandlerUNbPvZv' can not be used when making a shared object; recompile with -fPIC
```

These are the steps I followed:
```
$> git clone git@github.com:sociomantic-tsunami/dmd-transitional.git
$> cd dmd-transitional
$> git submodule update --init
$> make
```

Could you please let me know how I can proceed?

**Comment by Burgos** [comment]
It's probably `fPIC` issue and the new Ubuntu. See this:

https://issues.dlang.org/show_bug.cgi?id=17375
http://forum.dlang.org/thread/btxgztxksjwbxcojhdpr@forum.dlang.org?page=1
http://forum.dlang.org/thread/izzhrgnxkkvjgctdfacs@forum.dlang.org?page=1
https://github.com/dlang/dmd/commit/78cd023c4b5b7ac8d208b60369a52d0577083da5

etc 

I don't have such system, so I'm not 100% sure, but putting `-fPIC` in the makefile like this:

https://github.com/dlang/dmd/commit/9fbce55814bdc8f78d6fead3243db657eafc4ec7

Should do the trick.

**Comment by Burgos** [comment]
Also

https://github.com/dlang/installer/pull/207/files

**Comment by gkotian** [comment]
I am trying the build on Ubuntu 17.04, so it may indeed be related to the `-fPIC` issue that you linked.
I tried adding `override DFLAGS += -fPIC PIC=1` to the `Build.mak` file, but that didn't help :(

**Comment by mihails-strasuns-sociomantic** [comment]
I am afraid this is going to be `wont fix` issue. Mandatory `PIE` requirement in Ubuntu 17+ is going to be a huge pain in our ass (we could backport related fixes to dmd-transitional but now way for dmd1) and this is known. It is going to be impossible to upgrade to those Ubuntu versions until 100% of our code is migrated to D2 and by that time `dmd-transitional` version is also certain to be different.

**Comment by leandro-lucarella-sociomantic** [comment]
Could you elaborate a bit further?

**Comment by mihails-strasuns-sociomantic** [comment]
Starting with Ubuntu 17.04 distributed GCC requires all applications to be built with -fPIE (position independent executable, subset of -fPIC) option to be able to link against C stdlib. It required changes on the compiler side in D2 upstream to be able to compile even most trivial hello world program. But those changes used much larger work done previously to implement shared library support for D2 - nothing resembling that exists in D1 compiler making task of befriending it with Ubuntu 17.04+ pretty much impossible.

**Comment by leandro-lucarella-sociomantic** [comment]
I see, thanks! Is a huge bummer, but OTOH this might give us the final pressure hit to try to finalize the D2 migration by 2018 (next LTS should be 18.04, but we probably won't adopt it for the first few months).
